# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_auto_20170807_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nombre',
        ),
    ]
