# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_auto_20170815_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('carne', models.CharField(max_length=30)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
