# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0006_estudianteadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Estudiante',
        ),
    ]
