# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0007_auto_20170901_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('articulo', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.Estudiante')),
                ('estudianteAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.EstudianteAdmin')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.Articulo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.Estudiante')),
            ],
        ),
    ]
